# Generated by Django 2.2.12 on 2021-08-27 14:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoTasks',
            new_name='TodoTask',
        ),
    ]
